### ISSUE TITLE
请问databinding 一直报错。

### ISSUE THREAD

**Issue by i91h1r** [qingmei2/MultiTypeBindings#1]
<img width="527" alt="111" src="https://user-images.githubusercontent.com/15108892/38845713-65d5a298-422b-11e8-9159-5b08636d9151.png">
<img width="823" alt="112" src="https://user-images.githubusercontent.com/15108892/38845743-78ec41e8-422b-11e8-96a6-3a1e234ab883.png">

将app:onBindItem="@{fragment::onBindItem}" 去掉 就报这个：
<img width="972" alt="113" src="https://user-images.githubusercontent.com/15108892/38845797-bfb80292-422b-11e8-94a1-ea468b6ab32e.png">

**Comment by qingmei2** [comment]
@hyr0318 

是的，app:onBindItem="@{fragment::onBindItem}"这行代码，实际上是运行了您Activity中的onBindItem()回调，但您仍需要将这个属性在您的xml中进行声明，并在容器中（Fragment/Activity）中实现这个方法（哪怕这个方法是空的实现）。
