### ISSUE TITLE
竖向RecyclerView嵌套横向RecyclerView的问题

### ISSUE THREAD

**Issue by lan523503975** [qingmei2/MultiTypeBindings#2]
您好 这个库貌似不支持这样的嵌套，因为第二个recyclerView无法显示数据，我应该如何操作，是应该在onBindItem中自己去改吗

**Comment by qingmei2** [comment]
@lan523503975 

您好。

[MultiTypeBindings](https://github.com/qingmei2/MultiTypeBindings) 的目的是 **提供实现列表的一种思路**。

我不希望它作为依赖，成为项目中的一个工具，因为它虽然使用起来很方便，但是简单的API必然是隐藏了很多参数的注入和实现，这意味着更多的 **耦合**。

目前MultiTypeBindings是不支持 RecyclerView嵌套的需求的，这可能需要 开发者在其本身的设计中再独立开发出一套对应的API，就像单类型列表和多类型列表时， **app:itemLayout** 和 **app:linkers** 属性的设计一样。
